### ISSUE TITLE
unable to save session in socket.io

### ISSUE THREAD

**Issue by tbenst** [LnsooXD/koa-socket-session#1]
First of all, thank you for making this! Very convenient.

I am unable to make permanent changes to the session from socket.io, although I am able to read the session. Is there a way to modify the session from socket.io?

Can read and write:

```
router.get('/count', ctx => {
    var session = ctx.session;
    session.count = session.count || 0;
    session.count++;
    ctx.body = session.count;
})
```

Can only read:

```
io.on('test', (ctx, data) => {
    var session = ctx.session;
    session.count = session.count || 0;
    session.count++;
    console.log('test get count', ctx.session.count)
})
```

**Comment by LnsooXD** [comment]
I'm so sorry that i was in holiday a few days. I will check the issues.

**Comment by tbenst** [comment]
Enjoy your holiday! When you are back, let me know if I can help troubleshoot.

**Comment by niftylettuce** [comment]
something like `ctx.sessionStore.set(ctx.sessionId, ctx.session)`

**Comment by LnsooXD** [comment]
@tbenst Did you solve this problem yet? I solved a problem in module `cookies`. And The code above works fine in my project.
